import type { TenantConfig } from '@/core/config/tenant';
import { defaultThresholds } from '@/core/config/tenant';

/**
 * Tenant #01 — STIDC SEJAHTERA360.
 * This file is configuration, not code. Nothing here is imported by the core.
 */
export const stidc: TenantConfig = {
  id: 'stidc',
  organisationName: 'Sarawak Timber Industry Development Corporation',
  organisationCode: 'STIDC',
  shortName: 'STIDC',
  productName: 'SEJAHTERA360',
  tagline: 'From Medical Claims to Proactive Wellbeing',
  logoMark: 'S360',
  welcomeText: 'Your benefit, your wellbeing, in one place.',
  locale: 'en-MY',
  theme: {
    canvas: '#080D1A',
    surface: '#111930',
    raised: '#18223A',
    line: '#222F4E',
    head: '#E9F0FF',
    primary: '#00D4B8',
    onPrimary: '#051418',
    tint: '#BED6FF',
    brand: '#00D4B8',
    violet: '#7C6CFF',
    gold: '#FFB84D',
    ink: '#CDD8F0',
    inkMuted: '#8F9EC0',
    inkSoft: '#677698',
    ok: '#22C79B',
    warn: '#FFB020',
    risk: '#FF5D6C',
    info: '#4CA5FF',
  },
  themeLight: {
    canvas: '#F2F7F7',
    surface: '#FFFFFF',
    raised: '#EAF3F4',
    line: '#D3E3E5',
    head: '#07312F',
    primary: '#0E9F8C',
    onPrimary: '#FFFFFF',
    tint: '#0E4B47',
    brand: '#0E9F8C',
    violet: '#6355D8',
    gold: '#C9821B',
    ink: '#28504E',
    inkMuted: '#5A7B79',
    inkSoft: '#87A3A1',
    ok: '#128C6E',
    warn: '#B7770D',
    risk: '#C63A47',
    info: '#1E6FB8',
  },
  terminology: {
    benefit: 'Medical Benefit',
    benefitShort: 'Benefit',
    wallet: 'Medical Benefit Wallet',
    employee: 'Staff member',
    employees: 'Staff',
    unitSingular: 'Division',
    unitPlural: 'Divisions',
    clinic: 'Panel Clinic',
    clinics: 'Panel Clinics',
    programme: 'Programme',
    programmes: 'Programmes',
    journey: 'My Sejahtera Journey',
    pulse: 'Wellbeing Pulse',
    currency: 'RM',
    currencyCode: 'MYR',
  },
  modules: {
    'medical-benefit': true,
    'panel-clinic': true,
    'employee-wellbeing': true,
    'health-screening': true,
    'activity-challenge': true,
    'mental-wellbeing': true,
    ergonomics: true,
    'preventive-campaigns': true,
    'absenteeism-insights': true,
    'wellness-rewards': false,
    'esg-reporting': true,
    'annual-wellbeing-report': true,
    'wellbeing-pulse': true,
    'intelligence-signals': true,
  },
  policies: [
    {
      id: 'pol-standard',
      name: 'Standard Outpatient Medical Benefit',
      annualAmount: 2500,
      period: 'calendar-year',
      serviceCategories: [
        'General consultation',
        'Medication',
        'Dental',
        'Optical',
        'Specialist referral',
        'Diagnostic / lab',
        'Physiotherapy',
      ],
      eligibility: { categories: ['Permanent', 'Contract'], minMonthsService: 3 },
      thresholds: defaultThresholds,
      approval: {
        autoApproveUnder: 300,
        approverRoles: ['hr', 'finance'],
        allowExcess: true,
      },
      carryForward: false,
    },
  ],
  defaultPolicyId: 'pol-standard',
  organisation: {
    divisions: [
      { name: 'Corporate Services', departments: ['Human Resources', 'Finance', 'Administration'] },
      { name: 'Industry Development', departments: ['Downstream Development', 'Entrepreneur Development'] },
      { name: 'Forestry & Compliance', departments: ['Licensing', 'Enforcement', 'Field Operations'] },
      { name: 'Technical Services', departments: ['Engineering', 'Facilities', 'Laboratory'] },
      { name: 'Strategy & Digital', departments: ['Corporate Planning', 'Digital Services'] },
      { name: 'Regional Offices', departments: ['Miri Regional', 'Sibu Regional', 'Bintulu Regional'] },
    ],
    locations: ['Kuching', 'Sibu', 'Bintulu', 'Miri', 'Sarikei'],
    employeeCategories: ['Permanent', 'Contract', 'Temporary'],
    grades: ['Grade 41', 'Grade 44', 'Grade 48', 'Grade 52', 'Grade 54', 'Support I', 'Support II'],
  },
  journey: [
    { key: 'know', title: 'Know', subtitle: 'Understand your benefit', description: 'See your entitlement, what you have used and what remains — in plain language.', href: '/app/benefit', icon: 'know' },
    { key: 'check', title: 'Check', subtitle: 'Wellbeing pulse & screening', description: 'A short, voluntary check-in and your health screening opportunities.', href: '/app/wellbeing', icon: 'check' },
    { key: 'prevent', title: 'Prevent', subtitle: 'Personal nudges', description: 'Quiet, supportive reminders before small things become large ones.', href: '/app/wellbeing', icon: 'prevent' },
    { key: 'participate', title: 'Participate', subtitle: 'Organisation programmes', description: 'Join screening, movement and resilience programmes open to you.', href: '/app/programmes', icon: 'participate' },
    { key: 'improve', title: 'Improve', subtitle: 'Personal goals', description: 'Set a goal that matters to you and track it privately.', href: '/app/wellbeing', icon: 'improve' },
    { key: 'thrive', title: 'Thrive', subtitle: 'A better working life', description: 'Fewer surprises, less paperwork, more support when you need it.', href: '/app/overview', icon: 'thrive' },
  ],
  programmeCategories: [
    'Health Screening',
    'Ergonomics',
    'Movement Challenge',
    'Resilience & Mental Wellbeing',
    'Nutrition Awareness',
    'Preventive Campaign',
  ],
  serviceCategories: [
    'General consultation',
    'Medication',
    'Dental',
    'Optical',
    'Specialist referral',
    'Diagnostic / lab',
    'Physiotherapy',
  ],
  privacy: {
    minimumAggregationGroup: 5,
    optionalConsents: [
      { purpose: 'aggregate-wellbeing', title: 'Contribute my wellbeing pulse anonymously', description: 'Your individual answers stay private. Only combined, anonymous patterns for groups of 5 or more reach the organisation.', defaultGranted: true },
      { purpose: 'programme-invitations', title: 'Invite me to relevant programmes', description: 'Allows the wellbeing team to invite you to programmes that match your interests. No medical information is used.', defaultGranted: true },
      { purpose: 'screening-results-to-wellbeing-team', title: 'Share my screening attendance with the wellbeing team', description: 'Attendance only — never your readings or results.', defaultGranted: false },
      { purpose: 'benefit-reminders', title: 'Send me benefit utilisation reminders', description: 'Supportive reminders as you approach your entitlement thresholds.', defaultGranted: true },
    ],
    retentionMonths: { transactions: 84, wellbeing: 24, audit: 84 },
    disclosure: [
      { audience: 'Human Resources', canSee: ['Your eligibility and entitlement', 'Claim and transaction status', 'MC dates recorded through panel clinics', 'Exception cases raised on your record'], cannotSee: ['Your wellbeing pulse answers', 'Your personal goals', 'Your screening readings', 'Your private notes'] },
      { audience: 'Finance', canSee: ['Transaction values and utilisation', 'Budget exposure and recovery cases'], cannotSee: ['Any wellbeing information', 'Diagnosis or clinical detail', 'Your screening results'] },
      { audience: 'Panel clinic', canSee: ['Your name, staff number and eligibility', 'Your remaining balance at the point of visit'], cannotSee: ['Your other clinic visits', 'Your wellbeing information', 'Your salary or grade'] },
      { audience: 'Wellbeing team', canSee: ['Programme registrations you make', 'Anonymous, combined wellbeing patterns'], cannotSee: ['Your individual pulse answers', 'Your medical claims', 'Who reported what'] },
      { audience: 'Management', canSee: ['Organisation-wide trends and forecasts', 'Programme participation rates', 'Anonymous wellbeing signals'], cannotSee: ['Any individual medical record', 'Any named wellbeing data', 'Groups smaller than 5'] },
    ],
  },
  managementKpis: [
    { key: 'totalEmployees', label: 'Total staff' },
    { key: 'eligibleEmployees', label: 'Eligible staff' },
    { key: 'ytdUtilisation', label: 'YTD utilisation', hint: 'Approved spend against total entitlement' },
    { key: 'budgetUtilised', label: 'Budget utilised' },
    { key: 'projectedYearEnd', label: 'Projected year-end' },
    { key: 'aboveThreshold', label: 'Above policy threshold' },
    { key: 'pendingExceptions', label: 'Open exceptions' },
    { key: 'programmeParticipation', label: 'Programme participation' },
    { key: 'screeningParticipation', label: 'Screening participation' },
    { key: 'wellbeingIndex', label: 'Wellbeing signal index' },
  ],
  reports: [
    { key: 'utilisation', name: 'Medical Benefit Utilisation Report', description: 'Utilisation by division, location and category for the selected period.', audience: ['hr', 'finance', 'management', 'admin'], zone: 'zone1' },
    { key: 'financial', name: 'Financial Governance Report', description: 'Committed, approved, forecast and recovery exposure.', audience: ['finance', 'management', 'admin'], zone: 'zone1' },
    { key: 'exceptions', name: 'Exception Report', description: 'Open, ageing and resolved exception cases with ownership.', audience: ['hr', 'finance', 'management', 'admin'], zone: 'zone1' },
    { key: 'experience', name: 'Employee Experience Report', description: 'Adoption, turnaround time and self-service indicators.', audience: ['hr', 'management', 'admin'], zone: 'zone3' },
    { key: 'participation', name: 'Wellbeing Participation Report', description: 'Programme and screening participation by group, suppressed below the aggregation floor.', audience: ['wellbeing', 'hr', 'management', 'admin'], zone: 'zone3' },
    { key: 'governance', name: 'Governance & Consent Report', description: 'Consent posture, access events and audit completeness.', audience: ['admin', 'management'], zone: 'zone1' },
    { key: 'management', name: 'Management Summary', description: 'One-page organisational position for the leadership meeting.', audience: ['management', 'admin'], zone: 'zone3' },
    { key: 'annual', name: 'Annual Workforce Wellbeing Report', description: 'Year in review: utilisation, participation, signals, interventions and outcomes.', audience: ['management', 'wellbeing', 'admin'], zone: 'zone3' },
  ],
  seed: { employees: 128, clinics: 10, months: 12, randomSeed: 20260822 },
};
