import type { Metadata } from 'next';
import { DocPage } from '../components/DocPage';
import { site } from '@/content/site';
import { AMOUNTS, formatRM } from '@/lib/rules';

export const metadata: Metadata = { title: `Contribution Terms · ${site.brand}` };

export default function Terms() {
  return (
    <DocPage title="Contribution Terms" updated="1 October 2026">
      <h2>About this portal</h2>
      <p>
        This portal is operated for {site.formalName}, a regional alumni chapter. It is not an official system of
        Universiti Tun Hussein Onn Malaysia. Official university alumni and career services are provided by UTHM through
        the Career &amp; Alumni Centre (PKKA).
      </p>
      <h2>Payment arrangement</h2>
      <p>
        {site.formalName} currently operates through an interim administrative arrangement. Contributions and
        programme-related payments are facilitated through {site.facilitator}, which provides the administrative and
        payment infrastructure. Each contribution is recorded according to its stated purpose for {site.formalName}{' '}
        activities and initiatives.
      </p>
      <h2>Payments and receipts</h2>
      <ul>
        <li>Payments are processed securely by ToyyibPay.</li>
        <li>
          Individual contributions start from {formatRM(AMOUNTS.individual.min)}; corporate contributions start from{' '}
          {formatRM(AMOUNTS.corporate.min)}.
        </li>
        <li>
          A payment / contribution acknowledgement is issued and emailed only after the payment has been verified with
          ToyyibPay. Cancelled or unsuccessful payments do not generate a receipt.
        </li>
        <li>
          The acknowledgement is generated by this contribution portal. It is not an official UTHM receipt and does not
          by itself confer tax relief.
        </li>
      </ul>
      <h2>Corporate recognition</h2>
      <p>
        Recognition such as acknowledgement in alumni programmes, appreciation letters or plaques is subject to
        eligibility and approval, including by the relevant UTHM office where applicable. It is not guaranteed by making a
        contribution.
      </p>
      <h2>Refunds and corrections</h2>
      <p>
        Contributions are generally non-refundable. If you made a payment in error, such as a duplicate payment or a wrong
        amount, contact us with your Contribution ID and we will review it.
      </p>
      <h2 id="contact">Contact</h2>
      <p>
        {site.contactEmail ? (
          <>
            Email <a href={`mailto:${site.contactEmail}`}>{site.contactEmail}</a> and include your Contribution ID if
            your question is about a payment.
          </>
        ) : (
          <>Reply to your receipt email and include your Contribution ID if your question is about a payment.</>
        )}
      </p>
    </DocPage>
  );
}
