// Mobile menu toggle
const burger = document.getElementById('burger');
const nav = document.getElementById('nav');
if (burger) {
  burger.addEventListener('click', () => {
    nav.classList.toggle('open');
  });
  document.querySelectorAll('.mobile-menu a').forEach(link => {
    link.addEventListener('click', () => nav.classList.remove('open'));
  });
}

// Scroll reveal
const revealEls = document.querySelectorAll('.reveal');
const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('in-view');
      observer.unobserve(entry.target);
    }
  });
}, { threshold: 0.15 });
revealEls.forEach(el => observer.observe(el));

// ============ Translations ============
const translations = {
  en: {
    'nav.about': 'About', 'nav.services': 'Services', 'nav.why': 'Why Us', 'nav.location': 'Location', 'nav.cta': 'Book a Cut',
    'hero.eyebrow': 'PETRA JAYA · KUCHING · SARAWAK',
    'hero.title1': 'FRESH CUT.',
    'hero.title2': 'FRESH CONFIDENCE.',
    'hero.sub': "A modern community barbershop for students, professionals and families — sharp fades, friendly faces, and prices that make sense for Petra Jaya.",
    'hero.cta1': 'Book a Cut →', 'hero.cta2': 'Explore Services',
    'hero.stat1': 'Open Daily',
    'hero.stat2num': 'Affordable', 'hero.stat2': 'Honest Pricing',
    'hero.stat3num': 'Modern', 'hero.stat3': 'Fade &amp; Style Experts',
    'about.kicker': 'WHO WE ARE',
    'about.title': 'Your Style.<br>Your Confidence.',
    'about.lead': "Built for today's generation, Hit Barber Astana goes beyond the haircut. We help you express your personality, build confidence, and stay current — every single visit.",
    'about.card1.title': 'The Vision',
    'about.card1.body': 'To become the most trusted and preferred community barbershop for young people, families, and working adults in Petra Jaya and beyond.',
    'about.card2.title': 'The Mission',
    'about.card2.body': 'To deliver quality grooming experiences through skilled craftsmanship, modern styling, excellent customer service, and affordable pricing.',
    'about.card3.title': 'The Belief',
    'about.card3.body': "We don't just cut hair. We engineer positive energy and self-belief — so you walk out feeling like the best version of yourself.",
    'services.kicker': 'THE GROOMING ECOSYSTEM',
    'services.title': 'A complete lifecycle —<br>styled in the chair, ready between visits.',
    'services.card1.title': 'The Cut',
    'services.card1.li1': 'Modern Fade Cuts',
    'services.card1.li2': 'Classic Haircuts',
    'services.card1.li3': 'Student Cuts',
    'services.card1.li4': "Children's Haircuts",
    'services.card1.li5': 'Senior Citizen Haircuts',
    'services.card2.title': 'The Care',
    'services.card2.li1': 'Hair Wash &amp; Massage',
    'services.card2.li2': 'Backwash Service',
    'services.card2.li3': 'Hair Treatment',
    'services.card2.li4': 'Hair Consultation',
    'services.card2.li5': 'Beard &amp; Mustache Grooming',
    'services.card3.title': 'The Keep',
    'services.card3.li1': 'Pomade &amp; Hair Clay',
    'services.card3.li2': 'Styling Products',
    'services.card3.li3': 'Hair Serum &amp; Tonic',
    'services.card3.li4': 'Beard Oil',
    'services.card3.li5': 'Leave-In Conditioner &amp; Accessories',
    'why.kicker': 'WHY HIT BARBER WINS',
    'why.title': 'Not premium. Not cheap.<br>Just <span class="accent-text">right</span> for Petra Jaya.',
    'why.card1.title': 'Modern Styles That Matter',
    'why.card1.body': 'Understanding today\'s trends — fades, textures and cuts that are Instagram &amp; TikTok-ready.',
    'why.card2.title': 'Skilled &amp; Passionate Barbers',
    'why.card2.body': 'Care, precision and detail in every chair, every single time.',
    'why.card3.title': 'Affordable &amp; Accessible',
    'why.card3.body': 'Prices that make sense for Petra Jaya — quality grooming for everyone.',
    'why.card4.title': 'Comfortable Environment',
    'why.card4.body': 'A clean, positive, relaxing space that feels like a welcome — not a wait.',
    'why.card5.title': 'Consistent Service',
    'why.card5.body': 'Reliable quality on every single visit, so you always know what to expect.',
    'why.card6.title': 'Real Community Connection',
    'why.card6.body': 'Relationships over transactions — growing together with the people around us.',
    'dna.tag': 'CREATIVE · CONFIDENT · ENERGETIC · AUTHENTIC',
    'dna.item1.title': 'Trendy', 'dna.item1.body': 'Updated styles &amp; modern techniques.',
    'dna.item2.title': 'Confident', 'dna.item2.body': 'Fostering positive energy.',
    'dna.item3.title': 'Friendly', 'dna.item3.body': 'Every customer welcomed like a friend.',
    'dna.item4.title': 'Affordable', 'dna.item4.body': 'Quality grooming for everyone.',
    'dna.item5.title': 'Customer-First', 'dna.item5.body': 'Relationships &amp; satisfaction guaranteed.',
    'dna.banner': 'COMMUNITY — Growing together with the people around us.',
    'location.kicker': 'VISIT US',
    'location.title': 'Walk in. Walk out<br>with fresh confidence.',
    'location.addrlabel': 'Address',
    'location.addrval': 'Hit Barber Astana, Arked MARA Astana, Petra Jaya, Kuching, Sarawak',
    'location.hourslabel': 'Hours',
    'location.hoursval': 'Daily — 9:30 AM to 6:30 PM',
    'location.taglinelabel': 'Tagline',
    'location.taglineval': 'Fresh Styles. Great Vibes. Real Confidence. ✂️🔥',
    'location.cta': 'Get Directions →',
    'footer.tagline': 'Fresh Cut. Fresh Confidence. — Petra Jaya, Kuching, Sarawak.',
    'footer.copy': '© 2026 Hit Barber Astana. All rights reserved.',
    'footer.credit': 'This Digital Experience is Part of the <a href="https://www.kobisberhad.com" target="_blank" rel="noopener">KOBIS Berhad</a> Innovation Ecosystem',
  },
  bm: {
    'nav.about': 'Tentang', 'nav.services': 'Perkhidmatan', 'nav.why': 'Kenapa Kami', 'nav.location': 'Lokasi', 'nav.cta': 'Tempah Gunting',
    'hero.eyebrow': 'PETRA JAYA · KUCHING · SARAWAK',
    'hero.title1': 'GUNTINGAN SEGAR.',
    'hero.title2': 'KEYAKINAN SEGAR.',
    'hero.sub': 'Sebuah kedai gunting rambut komuniti moden untuk pelajar, profesional dan keluarga — fade yang kemas, layanan mesra, dan harga yang berpatutan untuk Petra Jaya.',
    'hero.cta1': 'Tempah Gunting →', 'hero.cta2': 'Lihat Perkhidmatan',
    'hero.stat1': 'Buka Setiap Hari',
    'hero.stat2num': 'Berpatutan', 'hero.stat2': 'Harga Jujur',
    'hero.stat3num': 'Moden', 'hero.stat3': 'Pakar Fade &amp; Gaya',
    'about.kicker': 'SIAPA KAMI',
    'about.title': 'Gaya Anda.<br>Keyakinan Anda.',
    'about.lead': 'Dibina untuk generasi hari ini, Hit Barber Astana lebih daripada sekadar gunting rambut. Kami membantu anda meluahkan personaliti, membina keyakinan, dan kekal terkini — pada setiap kunjungan.',
    'about.card1.title': 'Visi Kami',
    'about.card1.body': 'Menjadi kedai gunting rambut komuniti yang paling dipercayai dan digemari oleh golongan muda, keluarga dan pekerja di Petra Jaya dan sekitarnya.',
    'about.card2.title': 'Misi Kami',
    'about.card2.body': 'Memberikan pengalaman dandanan berkualiti melalui kemahiran, gaya moden, perkhidmatan pelanggan yang cemerlang, dan harga berpatutan.',
    'about.card3.title': 'Kepercayaan Kami',
    'about.card3.body': 'Kami bukan sekadar gunting rambut. Kami membina tenaga positif dan keyakinan diri — supaya anda keluar dengan rasa diri yang terbaik.',
    'services.kicker': 'EKOSISTEM DANDANAN',
    'services.title': 'Satu kitaran lengkap —<br>bergaya di kerusi, bersedia antara lawatan.',
    'services.card1.title': 'Guntingan',
    'services.card1.li1': 'Fade Moden',
    'services.card1.li2': 'Gunting Klasik',
    'services.card1.li3': 'Gunting Pelajar',
    'services.card1.li4': 'Gunting Kanak-Kanak',
    'services.card1.li5': 'Gunting Warga Emas',
    'services.card2.title': 'Penjagaan',
    'services.card2.li1': 'Cuci &amp; Urut Rambut',
    'services.card2.li2': 'Servis Backwash',
    'services.card2.li3': 'Rawatan Rambut',
    'services.card2.li4': 'Konsultasi Rambut',
    'services.card2.li5': 'Dandanan Janggut &amp; Misai',
    'services.card3.title': 'Penjagaan Lanjutan',
    'services.card3.li1': 'Pomade &amp; Hair Clay',
    'services.card3.li2': 'Produk Styling',
    'services.card3.li3': 'Serum &amp; Tonik Rambut',
    'services.card3.li4': 'Minyak Janggut',
    'services.card3.li5': 'Conditioner &amp; Aksesori',
    'why.kicker': 'KENAPA HIT BARBER MENANG',
    'why.title': 'Bukan premium. Bukan murah.<br>Tepat <span class="accent-text">sesuai</span> untuk Petra Jaya.',
    'why.card1.title': 'Gaya Moden Yang Penting',
    'why.card1.body': 'Memahami trend hari ini — fade, tekstur dan gaya yang sedia untuk Instagram &amp; TikTok.',
    'why.card2.title': 'Tukang Gunting Mahir &amp; Bersemangat',
    'why.card2.body': 'Penuh perhatian, ketepatan dan detail pada setiap kerusi, setiap masa.',
    'why.card3.title': 'Berpatutan &amp; Mudah Diakses',
    'why.card3.body': 'Harga yang berpatutan untuk Petra Jaya — dandanan berkualiti untuk semua.',
    'why.card4.title': 'Persekitaran Selesa',
    'why.card4.body': 'Ruang bersih, positif dan santai yang terasa seperti dialu-alukan — bukan menunggu.',
    'why.card5.title': 'Servis Konsisten',
    'why.card5.body': 'Kualiti boleh dipercayai pada setiap lawatan, jadi anda sentiasa tahu apa yang dijangka.',
    'why.card6.title': 'Hubungan Komuniti Sebenar',
    'why.card6.body': 'Hubungan mengatasi transaksi — membesar bersama masyarakat sekeliling kami.',
    'dna.tag': 'KREATIF · YAKIN · BERTENAGA · TULEN',
    'dna.item1.title': 'Trendi', 'dna.item1.body': 'Gaya terkini &amp; teknik moden.',
    'dna.item2.title': 'Yakin', 'dna.item2.body': 'Memupuk tenaga positif.',
    'dna.item3.title': 'Mesra', 'dna.item3.body': 'Setiap pelanggan dialu-alukan seperti rakan.',
    'dna.item4.title': 'Berpatutan', 'dna.item4.body': 'Dandanan berkualiti untuk semua.',
    'dna.item5.title': 'Pelanggan Diutamakan', 'dna.item5.body': 'Hubungan &amp; kepuasan terjamin.',
    'dna.banner': 'KOMUNITI — Membesar bersama masyarakat sekeliling kami.',
    'location.kicker': 'LAWATI KAMI',
    'location.title': 'Masuk. Keluar<br>dengan keyakinan segar.',
    'location.addrlabel': 'Alamat',
    'location.addrval': 'Hit Barber Astana, Arked MARA Astana, Petra Jaya, Kuching, Sarawak',
    'location.hourslabel': 'Waktu Operasi',
    'location.hoursval': 'Setiap Hari — 9:30 Pagi hingga 6:30 Petang',
    'location.taglinelabel': 'Slogan',
    'location.taglineval': 'Gaya Segar. Vibe Hebat. Keyakinan Sebenar. ✂️🔥',
    'location.cta': 'Dapatkan Arah →',
    'footer.tagline': 'Guntingan Segar. Keyakinan Segar. — Petra Jaya, Kuching, Sarawak.',
    'footer.copy': '© 2026 Hit Barber Astana. Hak cipta terpelihara.',
    'footer.credit': 'Pengalaman Digital Ini Adalah Sebahagian daripada Ekosistem Inovasi <a href="https://www.kobisberhad.com" target="_blank" rel="noopener">KOBIS Berhad</a>',
  },
  zh: {
    'nav.about': '关于我们', 'nav.services': '服务项目', 'nav.why': '我们的优势', 'nav.location': '地点', 'nav.cta': '预约理发',
    'hero.eyebrow': 'PETRA JAYA · 古晋 · 砂拉越',
    'hero.title1': '清爽剪发。',
    'hero.title2': '焕然自信。',
    'hero.sub': '一家面向学生、上班族与家庭的现代社区理发店 — 利落渐变、亲切服务，以及适合 Petra Jaya 的实惠价格。',
    'hero.cta1': '预约理发 →', 'hero.cta2': '查看服务',
    'hero.stat1': '每日营业',
    'hero.stat2num': '实惠', 'hero.stat2': '价格诚实',
    'hero.stat3num': '现代', 'hero.stat3': '渐变与造型专家',
    'about.kicker': '关于我们',
    'about.title': '你的风格。<br>你的自信。',
    'about.lead': 'Hit Barber Astana 为新世代而生，不只是剪发。我们帮助你展现个性、建立自信，并保持时尚 — 每一次到访都是如此。',
    'about.card1.title': '我们的愿景',
    'about.card1.body': '成为 Petra Jaya 及周边地区年轻人、家庭与上班族最信赖、最喜爱的社区理发店。',
    'about.card2.title': '我们的使命',
    'about.card2.body': '通过精湛的手艺、现代造型、优质的客户服务以及实惠的价格，提供高品质的美发体验。',
    'about.card3.title': '我们的信念',
    'about.card3.body': '我们不只是剪发，更是为你注入正能量与自信 — 让你以最好的状态走出店门。',
    'services.kicker': '美发生态系统',
    'services.title': '完整的服务流程 —<br>椅上造型，每次到访都准备就绪。',
    'services.card1.title': '剪发',
    'services.card1.li1': '现代渐变剪发',
    'services.card1.li2': '经典剪发',
    'services.card1.li3': '学生理发',
    'services.card1.li4': '儿童理发',
    'services.card1.li5': '长者理发',
    'services.card2.title': '护理',
    'services.card2.li1': '洗发与按摩',
    'services.card2.li2': '躺洗服务',
    'services.card2.li3': '头发护理',
    'services.card2.li4': '发型咨询',
    'services.card2.li5': '胡须与髭须修剪',
    'services.card3.title': '保养产品',
    'services.card3.li1': '发蜡与发泥',
    'services.card3.li2': '造型产品',
    'services.card3.li3': '精华液与发用滋养液',
    'services.card3.li4': '胡须油',
    'services.card3.li5': '免洗护发素与配件',
    'why.kicker': '为何选择 HIT BARBER',
    'why.title': '不走高端，也不廉价。<br>对 Petra Jaya 来说，<span class="accent-text">恰到好处</span>。',
    'why.card1.title': '紧贴潮流的现代风格',
    'why.card1.body': '紧跟当今潮流 — 渐变、纹理与适合 Instagram 及 TikTok 的造型。',
    'why.card2.title': '技艺精湛、充满热忱的理发师',
    'why.card2.body': '每一张椅子、每一次服务都用心、精准且注重细节。',
    'why.card3.title': '实惠又亲民',
    'why.card3.body': '适合 Petra Jaya 的价格 — 人人都能享有优质美发服务。',
    'why.card4.title': '舒适的环境',
    'why.card4.body': '干净、积极、放松的空间，让你感受到欢迎而非等待。',
    'why.card5.title': '一致的服务品质',
    'why.card5.body': '每次到访都享有可靠的品质，让你总能预期到满意的结果。',
    'why.card6.title': '真正的社区联系',
    'why.card6.body': '比起交易，我们更重视关系 — 与身边的人一起成长。',
    'dna.tag': '创意 · 自信 · 活力 · 真实',
    'dna.item1.title': '潮流', 'dna.item1.body': '紧贴最新风格与现代技术。',
    'dna.item2.title': '自信', 'dna.item2.body': '培养积极正能量。',
    'dna.item3.title': '友善', 'dna.item3.body': '每位顾客都受到朋友般的欢迎。',
    'dna.item4.title': '实惠', 'dna.item4.body': '人人都能享有优质美发服务。',
    'dna.item5.title': '顾客至上', 'dna.item5.body': '保证良好关系与满意度。',
    'dna.banner': '社区 — 与身边的人一起成长。',
    'location.kicker': '欢迎光临',
    'location.title': '走进来，<br>带着焕然自信走出去。',
    'location.addrlabel': '地址',
    'location.addrval': 'Hit Barber Astana, Arked MARA Astana, Petra Jaya, Kuching, Sarawak',
    'location.hourslabel': '营业时间',
    'location.hoursval': '每日 上午9:30 至 下午6:30',
    'location.taglinelabel': '口号',
    'location.taglineval': '清新造型。绝佳氛围。真正自信。✂️🔥',
    'location.cta': '获取路线 →',
    'footer.tagline': '清爽剪发，焕然自信 — Petra Jaya, 古晋, 砂拉越。',
    'footer.copy': '© 2026 Hit Barber Astana。版权所有。',
    'footer.credit': '此数字体验是 <a href="https://www.kobisberhad.com" target="_blank" rel="noopener">KOBIS Berhad</a> 创新生态系统的一部分',
  },
  ib: {
    'nav.about': 'Pasal Kami', 'nav.services': 'Pengawa', 'nav.why': 'Kenapa Kami', 'nav.location': 'Endur', 'nav.cta': 'Pesan Gunting',
    'hero.eyebrow': 'PETRA JAYA · KUCHING · SARAWAK',
    'hero.title1': 'GUNTING BARU.',
    'hero.title2': 'KEPECHAYA DIRI BARU.',
    'hero.sub': 'Kedai gunting komuniti ti moden ke pelajar, orang bekereja enggau bilik keluarga — fade ti manah, orang ti ramah, enggau reti ti chukup ke Petra Jaya.',
    'hero.cta1': 'Pesan Gunting →', 'hero.cta2': 'Peda Pengawa Kami',
    'hero.stat1': 'Buka Tiap Hari',
    'hero.stat2num': 'Reti Chukup', 'hero.stat2': 'Reti Ti Bujur',
    'hero.stat3num': 'Moden', 'hero.stat3': 'Pakar Fade &amp; Gaya',
    'about.kicker': 'PASAL KAMI',
    'about.title': 'Gaya Nuan.<br>Kepechaya Diri Nuan.',
    'about.lead': 'Dibengkah ke generasi diatu, Hit Barber Astana labih ari semina gunting buk. Kami nulung nuan nunjukka diri, ngembuan kepechaya diri, enggau tetap moden — tiap kali nuan datai.',
    'about.card1.title': 'Visi Kami',
    'about.card1.body': 'Deka nyadi kedai gunting komuniti ti dipechaya enggau dipilih bansa anak mensia, bilik keluarga, enggau orang bekereja di Petra Jaya enggau sekuliling.',
    'about.card2.title': 'Misi Kami',
    'about.card2.body': 'Meri pengalaman dandan ti manah ngena pengawa ti landik, gaya moden, pengawa pelanggan ti manah, enggau reti ti chukup.',
    'about.card3.title': 'Pechaya Kami',
    'about.card3.body': 'Kami ukai semina gunting buk. Kami meri tenaga positif enggau pechaya diri — ngambika nuan pulai enggau perasai diri ti manah.',
    'services.kicker': 'EKOSISTEM DANDAN',
    'services.title': 'Satu pengawa ti chukup —<br>bergaya di kerusi, sedia antara dua lawatan.',
    'services.card1.title': 'Gunting',
    'services.card1.li1': 'Fade Moden',
    'services.card1.li2': 'Gunting Lama',
    'services.card1.li3': 'Gunting Pelajar',
    'services.card1.li4': 'Gunting Anak Mit',
    'services.card1.li5': 'Gunting Orang Tuai',
    'services.card2.title': 'Pengintu',
    'services.card2.li1': 'Basu &amp; Urut Buk',
    'services.card2.li2': 'Pengawa Backwash',
    'services.card2.li3': 'Rawat Buk',
    'services.card2.li4': 'Bekonsultasi Pasal Buk',
    'services.card2.li5': 'Dandan Janggut',
    'services.card3.title': 'Barang Dandan',
    'services.card3.li1': 'Pomade &amp; Hair Clay',
    'services.card3.li2': 'Barang Styling',
    'services.card3.li3': 'Serum &amp; Tonik Buk',
    'services.card3.li4': 'Minyak Janggut',
    'services.card3.li5': 'Conditioner &amp; Aksesori',
    'why.kicker': 'KENAPA HIT BARBER MENANG',
    'why.title': 'Ukai premium. Ukai murah.<br><span class="accent-text">Sesuai</span> ke Petra Jaya.',
    'why.card1.title': 'Gaya Moden Ti Penting',
    'why.card1.body': 'Nemu trend diatu — fade, tekstur enggau gaya ti sedia ke Instagram &amp; TikTok.',
    'why.card2.title': 'Tukang Gunting Landik &amp; Bisi Semangat',
    'why.card2.body': 'Bisi perhatian, tepat enggau detail di tiap kerusi, tiap maya.',
    'why.card3.title': 'Reti Chukup &amp; Mudah Bulih',
    'why.card3.body': 'Reti ti chukup ke Petra Jaya — dandan ti manah ke semua.',
    'why.card4.title': 'Endur Ti Nyamai',
    'why.card4.body': 'Endur ti tuchi, positif enggau nyamai ti rasa baka dialu-aluka — ukai nungguka.',
    'why.card5.title': 'Pengawa Ti Tetap',
    'why.card5.body': 'Kualiti ti dipechaya tiap kali nuan datai, nuan nemu utai ti deka bulih.',
    'why.card6.title': 'Pengawa Komuniti Ti Bujur',
    'why.card6.body': 'Pekaul labih ari jual-beli — besai sama enggau orang ke sekuliling kami.',
    'dna.tag': 'KREATIF · PECHAYA DIRI · BETENAGA · BUJUR',
    'dna.item1.title': 'Trendi', 'dna.item1.body': 'Gaya baru &amp; teknik moden.',
    'dna.item2.title': 'Pechaya Diri', 'dna.item2.body': 'Ngasuh tenaga positif.',
    'dna.item3.title': 'Ramah', 'dna.item3.body': 'Tiap pelanggan dialu-aluka baka kawan.',
    'dna.item4.title': 'Reti Chukup', 'dna.item4.body': 'Dandan ti manah ke semua.',
    'dna.item5.title': 'Pelanggan Dulu', 'dna.item5.body': 'Pekaul &amp; pengerai ti dijamin.',
    'dna.banner': 'KOMUNITI — Besai sama enggau orang ke sekuliling kami.',
    'location.kicker': 'DATAI NGUNJUNGI KAMI',
    'location.title': 'Tama. Pansut<br>enggau kepechaya diri baru.',
    'location.addrlabel': 'Alamat',
    'location.addrval': 'Hit Barber Astana, Arked MARA Astana, Petra Jaya, Kuching, Sarawak',
    'location.hourslabel': 'Maya Pengawa',
    'location.hoursval': 'Tiap Hari — 9:30 Pagi nyentuk 6:30 Lemai',
    'location.taglinelabel': 'Slogan',
    'location.taglineval': 'Gaya Baru. Vibe Manah. Kepechaya Diri Bujur. ✂️🔥',
    'location.cta': 'Minta Jalai →',
    'footer.tagline': 'Gunting Baru. Kepechaya Diri Baru. — Petra Jaya, Kuching, Sarawak.',
    'footer.copy': '© 2026 Hit Barber Astana. Semua Hak Tedaun.',
    'footer.credit': 'Pengalaman Digital Tu Sebagi ari Ekosistem Inovasi <a href="https://www.kobisberhad.com" target="_blank" rel="noopener">KOBIS Berhad</a>',
  }
};

function applyLanguage(lang) {
  const dict = translations[lang];
  if (!dict) return;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const value = dict[key];
    if (value === undefined) return;
    if (value.includes('<') || value.includes('&')) {
      el.innerHTML = value;
    } else {
      el.textContent = value;
    }
  });
  document.documentElement.lang = lang;
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });
  localStorage.setItem('hba-lang', lang);
}

document.querySelectorAll('.lang-btn').forEach(btn => {
  btn.addEventListener('click', () => applyLanguage(btn.dataset.lang));
});

const savedLang = localStorage.getItem('hba-lang') || 'en';
applyLanguage(savedLang);
